export const teams = [
  { id: '1', name: 'Argentina', flag: '🇦🇷', group: 'A' },
  { id: '2', name: 'Brasil', flag: '🇧🇷', group: 'A' },
  { id: '3', name: 'España', flag: '🇪🇸', group: 'B' },
  { id: '4', name: 'Alemania', flag: '🇩🇪', group: 'B' },
  { id: '5', name: 'Francia', flag: '🇫🇷', group: 'C' },
  { id: '6', name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'C' },
  { id: '7', name: 'México', flag: '🇲🇽', group: 'D' },
  { id: '8', name: 'Estados Unidos', flag: '🇺🇸', group: 'D' },
  { id: '9', name: 'Canadá', flag: '🇨🇦', group: 'E' },
  { id: '10', name: 'Portugal', flag: '🇵🇹', group: 'E' },
  { id: '11', name: 'Italia', flag: '🇮🇹', group: 'F' },
  { id: '12', name: 'Países Bajos', flag: '🇳🇱', group: 'F' },
];

export const matches = [
  {
    id: '1',
    homeTeam: 'Argentina',
    awayTeam: 'Brasil',
    homeFlag: '🇦🇷',
    awayFlag: '🇧🇷',
    date: '2026-06-11',
    time: '15:00',
    stadium: 'Estadio Azteca',
    city: 'Ciudad de México',
    group: 'A',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: '2',
    homeTeam: 'España',
    awayTeam: 'Alemania',
    homeFlag: '🇪🇸',
    awayFlag: '🇩🇪',
    date: '2026-06-12',
    time: '18:00',
    stadium: 'SoFi Stadium',
    city: 'Los Ángeles',
    group: 'B',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: '3',
    homeTeam: 'Francia',
    awayTeam: 'Inglaterra',
    homeFlag: '🇫🇷',
    awayFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: '2026-06-13',
    time: '20:00',
    stadium: 'MetLife Stadium',
    city: 'Nueva York',
    group: 'C',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: '4',
    homeTeam: 'México',
    awayTeam: 'Estados Unidos',
    homeFlag: '🇲🇽',
    awayFlag: '🇺🇸',
    date: '2026-06-14',
    time: '19:00',
    stadium: 'AT&T Stadium',
    city: 'Dallas',
    group: 'D',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: '5',
    homeTeam: 'Canadá',
    awayTeam: 'Portugal',
    homeFlag: '🇨🇦',
    awayFlag: '🇵🇹',
    date: '2026-06-15',
    time: '16:00',
    stadium: 'BMO Field',
    city: 'Toronto',
    group: 'E',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: '6',
    homeTeam: 'Italia',
    awayTeam: 'Países Bajos',
    homeFlag: '🇮🇹',
    awayFlag: '🇳🇱',
    date: '2026-06-16',
    time: '17:00',
    stadium: 'Gillette Stadium',
    city: 'Boston',
    group: 'F',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
];

export const stadiums = [
  {
    id: '1',
    name: 'Estadio Azteca',
    city: 'Ciudad de México',
    country: 'México',
    capacity: 87523,
  },
  {
    id: '2',
    name: 'SoFi Stadium',
    city: 'Los Ángeles',
    country: 'Estados Unidos',
    capacity: 70240,
  },
  {
    id: '3',
    name: 'MetLife Stadium',
    city: 'Nueva York',
    country: 'Estados Unidos',
    capacity: 82500,
  },
  {
    id: '4',
    name: 'AT&T Stadium',
    city: 'Dallas',
    country: 'Estados Unidos',
    capacity: 80000,
  },
  {
    id: '5',
    name: 'BMO Field',
    city: 'Toronto',
    country: 'Canadá',
    capacity: 30000,
  },
  {
    id: '6',
    name: 'Gillette Stadium',
    city: 'Boston',
    country: 'Estados Unidos',
    capacity: 65878,
  },
];

export const albumStickers = [
  { id: '1', name: 'Lionel Messi', team: 'Argentina', number: 'ARG-1', rarity: 'legendary', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400' },
  { id: '2', name: 'Neymar Jr', team: 'Brasil', number: 'BRA-1', rarity: 'legendary', image: 'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=400' },
  { id: '3', name: 'Kylian Mbappé', team: 'Francia', number: 'FRA-1', rarity: 'legendary', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400' },
  { id: '4', name: 'Cristiano Ronaldo', team: 'Portugal', number: 'POR-1', rarity: 'legendary', image: 'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=400' },
  { id: '5', name: 'Estadio Azteca', team: 'Estadios', number: 'EST-1', rarity: 'rare', image: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=400' },
  { id: '6', name: 'Escudo Argentina', team: 'Argentina', number: 'ARG-ESC', rarity: 'common', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400' },
  { id: '7', name: 'Escudo Brasil', team: 'Brasil', number: 'BRA-ESC', rarity: 'common', image: 'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=400' },
  { id: '8', name: 'Escudo España', team: 'España', number: 'ESP-ESC', rarity: 'common', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400' },
];

export const ticketTypes = [
  {
    id: '1',
    matchId: '1',
    match: 'Argentina vs Brasil',
    category: 'VIP',
    price: 450,
    available: 12,
  },
  {
    id: '2',
    matchId: '1',
    match: 'Argentina vs Brasil',
    category: 'Preferente',
    price: 250,
    available: 45,
  },
  {
    id: '3',
    matchId: '1',
    match: 'Argentina vs Brasil',
    category: 'General',
    price: 120,
    available: 150,
  },
  {
    id: '4',
    matchId: '2',
    match: 'España vs Alemania',
    category: 'VIP',
    price: 400,
    available: 8,
  },
  {
    id: '5',
    matchId: '2',
    match: 'España vs Alemania',
    category: 'Preferente',
    price: 220,
    available: 60,
  },

];
